#!/bin/bash

# automatically change configuration of Mac OS X based on location

exec 2>&1 >> $HOME/Library/Logs/LocationChanger.log

sleep 3

ts() {
    date +"[%Y-%m-%d %H:%M] $*"
} 

# get various system information
SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | grep ' SSID:' | cut -d ':' -f 2 | tr -d ' '`
LOCATION_NAMES=`scselect | tail -n +2 | cut -d \( -f 2- | sed 's/)$//'`
CURRENT_LOCATION=`scselect | tail -n +2 | egrep '^\ +\*' | cut -d \( -f 2- | sed 's/)$//'`

ts "Connected to '$SSID'"

CONFIG_FILE="$HOME/.locations/locations.conf"

if [ -f $CONFIG_FILE ] && [ "$SSID" != "" ]; then
    NEW_SSID=`egrep "^$SSID=" $CONFIG_FILE | cut -d = -f 2`
    if [ "$NEW_SSID" != "" ]; then
        ts "Will switch the location to '$NEW_SSID' (configuration file)"
        SSID=$NEW_SSID
    else
        ts "Will switch the location to '$SSID'"
    fi
fi

if echo "$LOCATION_NAMES" | egrep -q "^$SSID$"; then
    NEW_LOCATION="$SSID"
elif [ "$SSID" != "" ]; then
    if echo "$LOCATION_NAMES" | egrep -q "^Automatic$"; then
        NEW_LOCATION=Automatic
        ts "Location '$SSID' was not found. Will default to 'Automatic'"
    else
        ts "Location '$SSID' was not found. The following locations are available: $LOCATION_NAMES"
        exit 1
    fi
fi

if [ "$NEW_LOCATION" != "" ]; then
    if [ "$NEW_LOCATION" != "$CURRENT_LOCATION" ]; then
        ts "Changing the location to '$NEW_LOCATION'"
        scselect "$NEW_LOCATION"
    else
        ts "Already at '$NEW_LOCATION'"
    fi
fi
